(function(){function C(){}function w(a,b){return 0==ha.call(a).indexOf("[object "+b)}function u(a){return a&&"/"==a.charAt(a.length-1)?a.substr(0,a.length-1):a}function A(a,b){var c,e,d,f;c=1;e=a;b&&(e=e.replace(ia,function(a,b,e,d){e&&c++;f=k;return d||""}));if(f){d=b.split("/");if(c>d)throw Error("attempt to access module beyond root of package: "+a);d.splice(d.length-c,c);return d.concat(e||[]).join("/")}return e}function q(a){var b=a.indexOf("!");return{M:a.substr(b+1),i:0<=b&&a.substr(0,b)}}
function t(){}function p(a,b){t.prototype=a||O;var c=new t;t.prototype=O;for(var e in b)c[e]=b[e];return c}function B(){function a(a,b,d){e.push([a,b,d])}function b(a,b){for(var d,c=0;d=e[c++];)(d=d[a])&&d(b)}var c,e,d;c=this;e=[];d=function(f,c){a=f?function(a){a&&a(c)}:function(a,b){b&&b(c)};d=C;b(f?0:1,c);b=C;e=m};this.t=function(b,d,e){a(b,d,e)};this.f=function(a){c.s=a;d(k,a)};this.d=function(a){c.ga=a;d(x,a)};this.p=function(a){b(2,a)}}function y(a,b,c,e){a instanceof B?a.t(b,c,e):b(a)}function E(a,
b,c){var e;return function(){0<=--a&&b&&(e=b.apply(m,arguments));0==a&&c&&c(e);return e}}function F(){function a(b,d,c,g){var i;i=h.g(j,m,[].concat(b));this.then=b=function(a,b){y(i,function(b){a&&a.apply(m,b)},function(a){if(b)b(a);else throw a;});return this};this.next=function(b,d,e){return new a(b,d,e,i)};d&&b(d,c);y(g,function(){h.h(i)})}var b=[].slice.call(arguments),c;w(b[0],"Object")&&(c=b.shift(),j=h.b(c,j),h.v(c));return new a(b[0],b[1],b[2])}function T(a){var b=a.id;if(b==m)if(G!==m)G=
{C:"Multiple anonymous defines in url"};else if(!(b=h.$()))G=a;if(b!=m){var c=n[b];b in n||(c=h.j(b,j).b,c=n[b]=h.z(c,b));if(!(c instanceof B))throw Error("duplicate define: "+b);c.fa=x;h.A(c,a)}}function ja(a){try{return eval(a)}catch(b){}}function U(){var a;a=o[ka]("link");a.rel="stylesheet";a.type="text/css";return a}function la(a,b,c){V.push({url:a,P:b,S:function(){c(Error(W))}});a=X.shift();!a&&Y.length<ma&&(a=o.createElement("style"),Y.push(a),J.appendChild(a));a&&P(a)}function P(a){var b;(b=
V.shift())?(a.onload=function(){b.P();P(a)},a.onerror=function(){b.S();P(a)},a.styleSheet.addImport(b.url)):(a.onload=a.onerror=D,X.push(a))}function Z(a,b,c){if(!H.load){var e,d,f;if(!a.href||o.readyState&&"complete"!=o.readyState)e=x;else{e=x;try{if(d=a.sheet)f=d.cssRules,e=null===f,!e&&"length"in f&&(d.insertRule("-curl-css-test {}",0),d.deleteRule(0),e=k)}catch(g){e=/security|denied/i.test(g.message)}}e?c():a.onload==D||!a.onload||aa(function(){Z(a,b,c)},b)}}function na(a,b,c,e){function d(){if(f.onload!=
D&&f.onload){f.onload=f.onerror=D;var a=function(){!o.readyState||"complete"==o.readyState?b():aa(a,10)};a()}}var f;f=U();f.onload=function(){H.load=H.load||k;d()};Z(f,e,d);f.onerror=function(){H.error=H.error||k;f.onload!=D&&f.onload&&(f.onload=f.onerror=D,c(Error(W)))};f.href=a;J.appendChild(f)}function D(){}var k=!0,x=!1,v=this.window||global,j,K,Q,L=v.document,R=L&&(L.head||L.getElementsByTagName("head")[0]),oa=R&&R.getElementsByTagName("base")[0]||null,ba={},ca={},M={},pa="addEventListener"in
v?{}:{loaded:1,complete:1},O={},ha=O.toString,m,n={},N=x,G,qa=/\?/,da=/^\/|^[^:]+:\/\//,ia=/(\.)(\.?)(?:$|\/([^\.\/]+.*)?)/g,ra=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,sa=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,S,h;h={O:function(a,b){return h.m(A(a,b))},m:function(a,b){return b.c&&a in b.c&&b.c[a].ba||a},n:function(a,b){a&&b.K&&0>a.indexOf("/")&&(a=u(b.K)+"/"+a);return a},g:function(a,b,c,e){function d(b){return h.m(A(b,g.id),a)}function f(b,c,f){var l,ea;l=c&&function(a){c.apply(m,
a)};if(w(b,"String")){b=d(b);f=n[b];ea=f instanceof B&&f.a;if(!(b in n))throw Error("Module not resolved: "+b);if(l)throw Error("require(id, callback) not allowed");return ea||f}y(h.h(h.g(a,g.id,b,e)),l,f)}var g;g=new B;g.id=b||"";g.aa=e;g.B=c;g.b=a;g.q=f;f.toUrl=function(b){return h.j(d(b),a).url};g.O=d;return g},z:function(a,b,c){var e,d,f;e=h.g(a,b,m,c);d=e.f;f=E(1,function(a){e.l=a;try{return h.T(e)}catch(b){e.d(b)}});e.f=function(a){y(c||N,function(){d(n[e.id]=f(a))})};e.D=function(a){y(c||N,
function(){e.a&&(f(a),e.p(ca))})};return e},Q:function(a,b,c,e){return h.g(a,c,m,e)},Z:function(a){return a.q},F:function(a){return a.a||(a.a={})},Y:function(a){var b=a.o;b||(b=a.o={id:a.id,uri:h.G(a),exports:h.F(a),config:function(){return a.b}},b.a=b.exports);return b},G:function(a){return a.url||(a.url=h.w(a.q.toUrl(a.id)),a.b)},b:function(a){var b,c,e,d,f,g;b=!a;a&&(h.b=h.J);a||(a={});e=a.apiName||"curl";d=a.apiContext||v;f=a.defineName||"define";g=a.defineContext||v;c=a.overwriteApi;!b&&K&&(v.curl=
K,K=x);if(!b&&!c&&d[e]&&d[e]!=F)throw Error(e+" already exists");d[e]=F;if(!b||!v.define){if(!b&&!c&&f in g&&g[f]!=Q)throw Error(f+" already exists");g[f]=Q=function(){var a=h.X(arguments);T(a)};Q.amd={plugins:k,jQuery:k,curl:"0.7.0"}}return h.J(a)},J:function(a,b){function c(a,b){var e,c,g,z,i;for(i in a){g=a[i];g.name=g.id||g.name||i;z=d;c=q(u(g.name||i));e=c.M;if(c=h.n(c.i,d))(z=f[c])||(z=f[c]=p(d),z.c=p(d.c),z.e=[]),delete a[i];if(b){c=g;var I=void 0;c.path=u(c.path||c.location||"");I=u(c.main)||
"main";"."!=I.charAt(0)&&(I="./"+I);c.ba=A(I,c.name+"/");c.b=c.config;c.b&&(c.b=p(d,c.b))}else c={path:u(g)};c.N=e.split("/").length;e?(z.c[e]=c,z.e.push(e)):z.u=h.L(g,d)}}function e(a){var b=a.c;a.da=RegExp("^("+a.e.sort(function(a,c){return b[c].N-b[a].N}).join("|").replace(/\/|\./g,"\\$&")+")(?=\\/|$)");delete a.e}var d,f,g;b||(b={});d=p(b,a);d.u=d.baseUrl||"";d.K=d.pluginPath||"curl/plugin";d.R=RegExp(d.dontAddFileExt||qa);d.c=p(b.c);f=a.plugins||{};d.plugins=p(b.plugins);for(g in f)d.plugins[h.n(g,
d)]=f[g];f=d.plugins;d.e=[];c(a.paths,x);c(a.packages,k);for(g in f){f[g]=p(d,f[g]);var i=f[g].e;i&&(f[g].e=i.concat(d.e),e(f[g]))}e(d);return d},v:function(a){var b;(b=a&&a.preloads)&&0<b.length&&y(N,function(){N=h.h(h.g(j,m,b,k))})},j:function(a,b){var c,e,d,f;c=b.c;d=da.test(a)?a:a.replace(b.da,function(a){e=c[a]||{};f=e.b;return e.path||""});return{b:f||j,url:h.L(d,b)}},L:function(a,b){var c=b.u;return c&&!da.test(a)?u(c)+"/"+a:a},w:function(a,b){return a+((b||j).R.test(a)?"":".js")},H:function(a,
b,c){var e=L.createElement("script");e.onload=e.onreadystatechange=function(c){c=c||v.event;if("load"==c.type||pa[e.readyState])delete M[a.id],e.onload=e.onreadystatechange=e.onerror="",b()};e.onerror=function(){c(Error("Syntax or http error: "+a.url))};e.type=a.I||"text/javascript";e.charset="utf-8";e.async=!a.ca;e.src=a.url;M[a.id]=e;R.insertBefore(e,oa);return e},U:function(a){var b=[],c;("string"==typeof a?a:a.toSource?a.toSource():a.toString()).replace(ra,"").replace(sa,function(a,d,f){f?c=c==
f?m:c:c||b.push(d);return""});return b},X:function(a){var b,c,e,d,f,g;f=a.length;e=a[f-1];d=w(e,"Function")?e.length:-1;2==f?w(a[0],"Array")?c=a[0]:b=a[0]:3==f&&(b=a[0],c=a[1]);!c&&0<d&&(g=k,c=["require","exports","module"].slice(0,d).concat(h.U(e)));return{id:b,l:c||[],r:0<=d?e:function(){return e},k:g}},T:function(a){var b;b=a.r.apply(a.k?a.a:m,a.l);b===m&&a.a&&(b=a.o?a.a=a.o.a:a.a);return b},A:function(a,b){a.r=b.r;a.k=b.k;a.B=b.l;h.h(a)},h:function(a){function b(a,b,c){g[b]=a;c&&s(a,b)}function c(b,
c){var e,d,f,g;e=E(1,function(a){d(a);l(a,c)});d=E(1,function(a){s(a,c)});f=h.V(b,a);(g=f instanceof B&&f.a)&&d(g);y(f,e,a.d,a.a&&function(a){f.a&&(a==ba?d(f.a):a==ca&&e(f.a))})}function e(){a.f(g)}var d,f,g,i,r,s,l;g=[];f=a.B;i=f.length;0==f.length&&e();s=E(i,b,function(){a.D&&a.D(g)});l=E(i,b,e);for(d=0;d<i;d++)r=f[d],r in S?(l(S[r](a),d,k),a.a&&a.p(ba)):r?c(r,d):l(m,d,k);return a},W:function(a){h.G(a);h.H(a,function(){var b=G;G=m;a.fa!==x&&(!b||b.C?a.d(Error(b&&b.C||"define() missing or duplicated: "+
a.url)):h.A(a,b))},a.d);return a},V:function(a,b){var c,e,d,f,g,i,r,s,l,k;c=b.O;e=b.aa;l=b.b||j;d=q(a);i=d.M;f=d.i?h.m(h.n(A(d.i,b.id),l),l):c(i);r=h.j(f,l);if(d.i)g=f;else if(g=r.b.moduleLoader)i=f,f=g,r=h.j(g,l);d=n[f];f in n||(d=n[f]=h.z(r.b,f,e),d.url=h.w(r.url,d.b),h.W(d));f==g&&(s=new B,k=l.plugins[g]||l,y(d,function(a){var b,d,f;f=a.dynamic;i="normalize"in a?a.normalize(i,c,k)||"":c(i);d=g+"!"+i;b=n[d];if(!(d in n)){b=h.Q(k,d,i,e);f||(n[d]=b);var r=function(a){b.f(a);f||(n[d]=a)};r.resolve=
r;r.reject=r.error=b.d;a.load(i,b.q,r,k)}s!=b&&y(b,s.f,s.d,s.p)},s.d));return s||d},$:function(){var a;if(!w(v.opera,"Opera"))for(var b in M)if("interactive"==M[b].readyState){a=b;break}return a}};S={require:h.Z,exports:h.F,module:h.Y};F.version="0.7.0";j=v.curl;"function"==typeof j?(K=j,j=x):v.curl=m;j=h.b(j);h.v(j);n.curl=F;n["curl/_privileged"]={core:h,cache:n,config:function(){return j},_define:T,_curl:F,Promise:B};var fa=this.document;define("curl/plugin/js",["curl/_privileged"],function(a){function b(b,
c,d){function e(){g||(f<new Date?d():setTimeout(e,10))}var f,g,h;f=(new Date).valueOf()+(b.ea||3E5);d&&b.a&&setTimeout(e,10);h=a.core.H(b,function(){g=k;b.a&&(b.s=ja(b.a));!b.a||b.s?c(h):d()},function(a){g=k;d(a)})}function c(a,e){b(a,function(){var b=d.shift();h=0<d.length;b&&c.apply(null,b);e.f(a.s||k)},function(a){e.d(a)})}var e={},d=[],f=fa&&fa.createElement("script").async==k,g,h;g=a.Promise;return{dynamic:k,load:function(a,s,l,m){function p(a){(l.error||function(a){throw a;})(a)}var j,n,q,t,
o;j=0<a.indexOf("!order");n=a.indexOf("!exports=");q=0<n&&a.substr(n+9);t="prefetch"in m?m.prefetch:k;a=j||0<n?a.substr(0,a.indexOf("!")):a;o=s.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".js":a);o in e?e[o]instanceof g?e[o].t(l,p):l(e[o]):(a={name:a,url:o,ca:j,a:q,ea:m.timeout},e[o]=s=new g,s.t(function(a){e[o]=a;l(a)},p),j&&!f&&h?(d.push([a,s]),t&&(a.I="text/cache",b(a,function(a){a&&a.parentNode.removeChild(a)},function(){}),a.I="")):(h=h||j,c(a,s)))}}});var ka="createElement",aa=this.setTimeout,
o=this.document,J,ta=o&&o.createStyleSheet&&!(10<=o.documentMode),Y=[],X=[],V=[],ma=12,ga,W="HTTP or network error.",H={};o&&(J=o.head||o.getElementsByTagName("head")[0],ga=ta?la:na);define("curl/plugin/css",{normalize:function(a,b){var c,e;if(!a)return a;c=a.split(",");e=[];for(var d=0,f=c.length;d<f;d++)e.push(b(c[d]));return e.join(",")},load:function(a,b,c,e){function d(){0==--k&&c()}function f(a){(c.d||function(a){throw a;})(a)}var g,h,k,j;g=(a||"").split(",");h=e.cssWatchPeriod||50;e=e.cssNoWait;
k=g.length;for(j=0;j<g.length;j++){var a=g[j],l,a=b.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".css":a);e?(l=U(),l.href=a,J.appendChild(l),d()):ga(a,d,f,h)}},"plugin-builder":"./builder/css",pluginBuilder:"./builder/css"})}).call(this);
(function(C){var w=C.document,u=function(q){for(var t={},q=q.substr(1).split("&"),p=q.length-1;p>=0;p--){var u=q[p].split("=");t[u[0]]=decodeURIComponent((u[1]||"").replace(/\+/g,"%20"))}return t}(location.search),A=function(q){return(q=w.getElementById("disqus-"+q))&&JSON.parse(q.textContent||q.innerHTML)};u.n_s?w.documentElement.className+=" not-supported type-"+u.n_s:C.onload=function(){var q=C.location.protocol=="https:";curl({baseUrl:q?"https://securecdn.disqus.com/1375737634":"http://mediacdn.disqus.com/1375737634"});
var t=[];t.push("js!/next/config.js?forum="+u.f+"!order");t.push("js!build/next/lib.js!order");t.push("js!build/next/lounge/client.js!order");q?t.push("css!build/next/styles/lounge_ssl.css"):t.push("css!build/next/styles/lounge.css");t.push("js!build/next/templates/lounge.js!order");curl(t).then(function(){var p=A("threadData");p.code?($("#postCompatContainer").hide(),$("#error").show(),DISQUS.Bus.sendHostMessage("fail",p)):(DISQUS.extend(p.response,A("forumData")),new DISQUS.next.views.Lounge({jsonData:p,
el:w.body}),DISQUS.next.lounge.tracking.init(DISQUS.next.views.Lounge.getInstance()))})}})(window);